# Generated by Django 5.0.1 on 2024-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
