# Generated by Django 5.0.1 on 2024-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_user_is_mod_user_address1_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='./media/profile_picture/avater.jpg', upload_to='media/profile_picture/'),
        ),
    ]
