# Generated by Django 5.0.1 on 2024-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_user_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='./Account/profile_picture/avater.jpg', upload_to='Account/profile_picture/'),
        ),
    ]
