# Generated by Django 5.0.1 on 2024-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_user_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='./static/avater.jpg', upload_to='profile_picture/'),
        ),
    ]
