# Generated by Django 5.0.1 on 2024-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_alter_publisher_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(default='./publisher/logo/default.jpg', upload_to='publisher/logo/'),
        ),
    ]
