# Generated by Django 5.0.1 on 2024-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_alter_publisher_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(default='./media/logo/publisher_default.jpg', upload_to='logo/'),
        ),
    ]
