# Generated by Django 5.0.1 on 2024-02-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_avater_alter_book_category_and_more'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='avater',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
