# Generated by Django 5.0.1 on 2024-02-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_publisher'),
        ('publisher', '0002_remove_publisher_is_approved_publisher_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='publisher.publisher'),
        ),
    ]
