# Generated by Django 5.0.1 on 2024-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='./media/book_cover/default.jpg', upload_to='media/book_cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
