# Generated by Django 5.0.1 on 2024-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='./book/book_cover/default.jpg', upload_to='book/book_cover/'),
        ),
    ]
