# Generated by Django 5.0.1 on 2024-02-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avater',
            field=models.ImageField(default='./book/author_avater/avater.jpg', upload_to='book/author_avater'),
        ),
    ]
