# Generated by Django 5.0.1 on 2024-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_author_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avater',
            field=models.ImageField(default='./static/avater.jpg', upload_to='author_avater/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='./static/default.jpg', upload_to='book_cover/'),
        ),
    ]
