# Generated by Django 5.0.1 on 2024-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_author_avater_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avater',
            field=models.ImageField(default='./author_avater/avater.jpg', upload_to='author_avater/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='./media/book_cover/default.jpg', upload_to='book_cover/'),
        ),
    ]
