# Generated by Django 5.0.1 on 2024-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_author_avater_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='./book_cover/default.jpg', upload_to='book_cover/'),
        ),
    ]
